# Generated by Django 4.1.7 on 2023-03-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
