# Generated by Django 4.1.7 on 2023-04-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_classtr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classtr',
            new_name='ClassTeacher',
        ),
    ]
