# Generated by Django 4.1.7 on 2023-04-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_classtr_classteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classteacher',
            old_name='cltrid',
            new_name='classTeacher_id',
        ),
    ]
